export interface Users {
    cpf : number,
    cpfConstaAnaliseEspecial:boolean,
    cpfConstaListaPep:boolean ,
    situacaoCpf:boolean,
    dataHoraAtu:string,
    "similaridadeNome": 1,
    "dataNascimentoProposta": 1,
    "cepEnderecoPreenchido": 1,
    "profissao":"Checar com CBO",
    "rendaDeclarada": 1,
    "limiteContribuicaoMensal": 1,
    "idadeProponente": 1,
    "propostasAtivasProponente": 1,
    "propostasAtivasResponsavelFinanceiro": 1,
    "propostasAtivasResponsavelLegal": 1,
    "perfilEtarioProponente": 1,
    "qtdeFuncionariosVidas": 1,
    "mediaSalarial": 1,
    "produtosContratados": 1,
    "riscoFaixaRenda": 1,
    "faixaRendaProfissao": 1,
    "parentesco": 1,
    "vinculo": 1
}
